remove text-decoding
fastify/busboy pull request #120
Opened 2023-08-13 18:47 UTC by KhafraDev

This was added in #50 for reasons I don't really understand. According to the PR node's TextDecoder is the fastest (and I assume it's even faster now), provides the same features, and is available globally since node v11.

2023-08-13 18:54 UTC, Uzlopak commented
It was for Backwards compatibility.

2023-08-13 19:00 UTC, Uzlopak approved these changes
LGTM

Added semver major label.

2023-08-13 19:17 UTC, kibertoad commented
@KhafraDev @Uzlopak wasn't it for compatibility with non-node runtimes, such as AtlasDB workers?

2023-08-13 19:19 UTC, kibertoad commented
no, https://github.com/fastify/busboy/issues/100 seems to be a different thing

2023-08-13 19:28 UTC, Uzlopak requested changes
Blocking till we investigate or come to a conclusion on how to avoid breaking too much

2023-08-13 19:50 UTC, Uzlopak commented
Talked with kibertoad. 

The issue with firebase_admin was that dicer does not need the TextDecoder.

2023-08-23 14:02 UTC, Uzlopak approved these changes
LGTM

2023-08-23 14:03 UTC, merged